### ISSUE TITLE
Allow multiple endpoints for etcd coordinator

### ISSUE THREAD

**Issue by choffmeister** [hseeberger/constructr#115]
To take advantage of etcd high availability cluster it would be nice to be able to define more than one endpoint. Should be not that hard to do.

@hseeberger If you agree, I would like to work on it and create a PR?

**Comment by hseeberger** [comment]
Does that make sense at all? Why not put etcd (or some other HA service) behind a reverse proxy? That way the actual endpoints are flexible.

**Comment by choffmeister** [comment]
I am currently just diving into running akka-cluster inside of kubernetes and am still wrapping my head around this stuff. So I might be totally wrong here :)

Is having a load-balancer in front of ETCD a good practise? When I need to update ETCD this should just work find with 100% uptime, but what if I have to update the load-balancer itself? If other components talk to ETCD via the load-balancer and not by probing the individual ETCD instances directly, then I have a crucial component in my distributed system which cannot be updated without down-time… Or am I wrong here?

**Comment by hseeberger** [comment]
Ah, well, yes, but why would you want to update the load balancer? BTW, a lot of platforms offer automatic load balancers, Docker Cloud or AWS, which you of course never have to update.

**Comment by hseeberger** [comment]
But anyway, I think it won't hurt to take a set of endpoints instead of a single one, so go for it!

**Comment by markusjura** [comment]
This is not only interesting for `etcd` but also other coordination services.

I'd like to see that the `constructr.coordination.host` and `constructr.coordination.port` format is changed to `constructr.coordination.nodes`. This value is a string list and can contain multiple coordination nodes such as:

```
constructr.coordination.nodes = ["10.0.0.10:2379", "10.0.0.11:2379", "10.0.0.12:2379"]
```

I'd be happy to provide a PR. However, I don't know how the etcd HTTP API used in the [EtcdCoordination](https://github.com/hseeberger/constructr/blob/master/constructr-coordination-etcd/src/main/scala/de/heikoseeberger/constructr/coordination/etcd/EtcdCoordination.scala#L49-L53) class could make us of multiple nodes? As far as I understand, it is only possible to send an HTTP request to one particular node, not too multiple. Ideas?

**Comment by markusjura** [comment]
Using multiple nodes in the [https://github.com/typesafehub/constructr-zookeeper] coordination service is easy once the `constructr.coordination.nodes` key is available. [curator](http://curator.apache.org/) is used as a high-level Zookeeper API and with that, you can specify multiple nodes when establishing a connection to a Zookeeper cluster.

**Comment by hseeberger** [comment]
I hear what you are saying. So far, I was thinking that one would access the (clustered) coordination service through a URI (host and port) representing a load balancer. I was thinking that this reflects real life scenarios much closer or better, because the clustered coordination service might eventually grow or shrink in size or simply change the set of URIs over time by adding new nodes and removing old ones – which is not well abstracted over with a set of URIs.

**Comment by markusjura** [comment]
Yes, this can be the case. But I think the other case of specifying multiple endpoints exists in the "real-world" as well. This is the default for every framework on Mesos, and of Mesos itself.

I'll try to submit a PR soon to support multiple endpoints not only for etcd, but for every possible coordination service implementation.

**Comment by markusjura** [comment]
FYI: I've created a PR for [constructr-zookeeper](https://github.com/typesafehub/constructr-zookeeper) that enables to specify multiple endpoints to join a multi-node ZK cluster: https://github.com/typesafehub/constructr-zookeeper/pull/10

I've also checked if I can do that for the `etcd` coordination service as well, but I couldn't find a simple way of doing this because here we are using a `URI` to connect to `etcd`. So I am not sure how to connect to a multi-node etcd cluster in such fashion.

**Comment by hseeberger** [comment]
OK, let's close this ticket then.
