### ISSUE TITLE
Using the consul service catalog

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#45]
When using consul, ConstructR currently uses the consul KV store both for storing the lock that determines whether there is already a seed node initializing, and for storing the addresses of seed nodes.

Wouldn't it make sense to use the consul service catalog to keep track of the addresses of seed nodes?

**Comment by hseeberger** [comment]
I don't know Consul well enough. @juanjovazquez, what do you think?

**Comment by juanjovazquez** [comment]
@raboof, I used consul KV store in order to maintain a parallelism between both coordination services, i.e. consul and etcd. Heiko started this project and set some guidelines that I followed to implement the consul support. Having said that, it's true that a solution based on the consul service catalog could result more idiomatic in terms of consul patterns and would enable apply the health checking mechanism.

We're now in the middle of a refactoring because of the issue #42. Please, let us finish this work and then we'll give some thought to your proposal.

BTW, @hseeberger I miss sometimes being able to discuss some design issues in a more informal manner. How would you see to enable Gitter?.

**Comment by hseeberger** [comment]
Not sure if this matters wrt idiomatic Consul usage, but currently this project is scoped to provide cluster construction – no service discovery, health checks, etc.

Yeah, let's go to Gitter!

**Comment by juanjovazquez** [comment]
@raboof, after giving it some thought, we've reached the conclusion that cluster construction and service discovery should remain separate. Currently, in our architecture every node in the cluster is announced by the scheduler ([nomad](https://hashicorp.com/blog/nomad.html) in our case, but could be fleet, kubernetes, etc) so that the cluster ends up being registered as a service in the consul service catalog also. I think that's the way to go.

So, as @hseeberger mentioned, I think that constructr should stick to cluster construction and therefore the solution based on consul KV store seems to be the proper one.

**Comment by raboof** [comment]
I agree completely that constructr should not directly write to the consul service catalog: that clearly is the responsibility of other tools (such as the ones you mention).

When checking if there are already healthy nodes available during cluster construction, my point was it'd make sense for the cluster construction mechanism (i.e. constructr) to consume/consult the separate service discovery mechanism (i.e. the consul service catalog). You could even say this way constructr "sticks to cluster construction" better, as it can avoid keeping track of healthy nodes (a service discovery concern) itself.

Anyway, the current solutions seems to work out fine, too, so I'll close this issue :).
